// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskForSteadyPoint;

namespace TaskForSteadyPoint.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TaskForSteadyPoint.Entities.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OfficialID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OfficialID")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreationDate = new DateTime(2021, 2, 9, 17, 25, 53, 8, DateTimeKind.Local).AddTicks(1644),
                            DateOfBirth = new DateTime(1998, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Ahmad@steady",
                            EmployeeName = "Ahmad",
                            OfficialID = 1
                        },
                        new
                        {
                            ID = 2,
                            CreationDate = new DateTime(2021, 2, 9, 17, 25, 53, 13, DateTimeKind.Local).AddTicks(3193),
                            DateOfBirth = new DateTime(1998, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "Anas@steady",
                            EmployeeName = "Anas",
                            OfficialID = 2
                        },
                        new
                        {
                            ID = 3,
                            CreationDate = new DateTime(2021, 2, 9, 17, 25, 53, 13, DateTimeKind.Local).AddTicks(3372),
                            DateOfBirth = new DateTime(2001, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "ihab@steady",
                            EmployeeName = "ihab",
                            OfficialID = 3
                        },
                        new
                        {
                            ID = 4,
                            CreationDate = new DateTime(2021, 2, 9, 17, 25, 53, 13, DateTimeKind.Local).AddTicks(3389),
                            DateOfBirth = new DateTime(2002, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "majd@steady",
                            EmployeeName = "majd",
                            OfficialID = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
